services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    hostname: my-rabbit
    container_name: some-rabbit
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro  # Mount config file (read-only)
    networks:
      - idekanin_default
    ports:
      - '15672:15672'
      - '5672:5672'

  arangodb:
    image: 'arangodb:3.11.6'
    hostname: my-arangodb
    container_name: some-arangodb
    environment:
      - ARANGO_ROOT_PASSWORD=${TOP_SECRET}
    env_file:
      - api-endpoints/.env.arangodb
    networks:
      - idekanin_default

  apiEndpoints:
    image: "com.demo.website:api-endpoints"
    hostname: "api-endpoints"
    container_name: "api-endpoints"
    ports:
      - "9081:8080"
    networks:
      - idekanin_default
    build:
      context: ./api-endpoints
    links:
      - "rabbitmq:some-rabbit"
      - "arangodb:some-arangodb"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  lookupworker1:
    image: "com.demo.website:lookup-worker1"
    hostname: "lookup-worker-1"
    container_name: "lookup-worker-1"
    ports:
      - "9085:8080"
    networks:
      - idekanin_default
    build:
      context: ./lookup-worker1
      dockerfile: DEV.Dockerfile
    links:
      - "apiEndpoints:api-endpoints"
      - "rabbitmq:some-rabbit"
    depends_on:
      apiEndpoints:
        condition: service_healthy

networks:
  idekanin_default:
    name: idekanin_default
    external: false