[{rabbit, [
            {loopback_users, [[{"name", "kanin"},
                                  {"password", "kanin"},
                                  {"tags", ["monitoring"]}, 
                                  {"rights", [[{"<<"">">", "<<"">">", []}, {"*", "*", ["read"]}]}]]]]
                                  }]