# RabbitMQ: connection details
rabbitmq-host=my-rabbit
rabbitmq-port=5672
rabbitmq-username=guest
rabbitmq-password=guest

# RabbitMQ: Incoming exchange, routing key & queue config
mp.messaging.incoming.idMapper.connector=smallrye-rabbitmq
mp.messaging.incoming.idMapper.exchange.name=exchange_id_mapper
mp.messaging.incoming.idMapper.exchange.type=direct
mp.messaging.incoming.idMapper.routing-keys=routing_id_lookup_with_ctx
mp.messaging.incoming.idMapper.queue.name=my_TESTAPP_queue_app1
