# RabbitMQ: connection details
rabbitmq-host=my-rabbit
rabbitmq-port=5672
rabbitmq-username=guest
rabbitmq-password=guest

# RabbitMQ: Outgoing exchange and routing key config
mp.messaging.outgoing.idMapper.connector=smallrye-rabbitmq
mp.messaging.outgoing.idMapper.exchange.name=exchange_id_mapper
mp.messaging.outgoing.idMapper.exchange.type=direct
mp.messaging.outgoing.idMapper.default-routing-key=routing_id_lookup_with_ctx

# ArangoDB
#%prod.
cache.hosts=my-arango:8529
cache.password=openSesame



# ****** #
# Uncomment the lines below only if app is running as standalone (not using docker compose)
# ****** #
# Change default port for Quarkus app:
#quarkus.http.port=8090