quarkus.http.port=8090

rabbitmq-host=localhost
rabbitmq-port=5672
rabbitmq-username=guest
rabbitmq-password=guest

mp.messaging.outgoing.idMapper.connector=smallrye-rabbitmq
mp.messaging.outgoing.idMapper.exchange.name=exchange_id_mapper
mp.messaging.outgoing.idMapper.exchange.type=direct
mp.messaging.outgoing.idMapper.default-routing-key=routing_id_lookup_with_ctx
